### ISSUE TITLE
RSSの<link>のURLが壊れているようです

### ISSUE THREAD

**Issue by MasayoshiMikitani** [leaysgur/posts#2]
毎記事、更新を楽しみにしております。

最近こちらのRSSの購読をし始めたのですが、RSSの `<link>` のURLから `posts` が欠けているようです。
https://leaysgur.github.io/posts/rss.xml

誤 : https://leaysgur.github.io/2024/07/09/125301/
正 : https://leaysgur.github.io/posts/2024/07/09/125301/

以上、ご報告まで🙏

**Comment by leaysgur** [comment]
ありがとうございます！助かります！

先ほど修正しました〜 🙌🏻 https://github.com/leaysgur/posts/commit/809499525c01e1a9535ec8e828cb2dc5b54902c0

![image](https://github.com/leaysgur/posts/assets/6259812/29f66046-bfdc-4919-a3cd-4dc59cea1ac4)

（楽しめる記事をお届けできるようぼちぼちがんばります 😎 ）
